In [5]:
#1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np 
(np.arange(10)==4).astype(int)


array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [6]:
#2. Create a vector with values ranging from 10 to 49.
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
x=np.array([1,2,0,0,4,0])
print("indices of non-zero elements are:",np.nonzero(x))

indices of non-zero elements are: (array([0, 1, 4], dtype=int64),)


In [9]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
import random
random.seed(10)
x=np.random.random(size=(10,10))
print("Minimum vales:",x.min())
print("Maximum values:",x.max())
print(x)


Minimum vales: 0.00032143771941417487
Maximum values: 0.996639743674005
[[9.25047728e-01 8.46801337e-03 2.51820013e-01 7.63886094e-01
  2.40903637e-01 4.39653273e-01 7.90989111e-01 9.38128518e-01
  8.32116172e-01 7.24384860e-01]
 [7.79862136e-01 7.67213825e-01 5.00622997e-01 8.75331956e-01
  7.06163088e-01 1.81163483e-01 5.28651632e-01 6.68416771e-01
  3.82700994e-01 2.67918270e-01]
 [2.25936282e-01 2.16502279e-01 5.55397400e-02 1.40254368e-01
  3.78725131e-01 5.05856648e-01 4.10007550e-01 3.94920046e-01
  7.00658299e-01 9.49961461e-01]
 [3.30817321e-01 9.63609321e-01 7.57169904e-01 2.69497436e-01
  1.65239605e-01 9.47242929e-01 9.53852219e-01 7.32282771e-01
  9.32925940e-01 8.91624540e-01]
 [6.23839274e-01 6.42364106e-01 4.10990476e-01 8.49066154e-01
  1.30439360e-01 3.61305869e-01 9.20671471e-01 7.28861036e-01
  1.69531913e-01 3.01287160e-02]
 [1.63076188e-02 9.49522571e-01 4.70192317e-01 5.88868896e-01
  6.76472334e-01 3.21437719e-04 7.41948806e-01 7.89164917e-01
  9.32141076e-01 9.

In [10]:
#6. Create a random vector of size 30 and find the mean value.
arr=np.random.random((5,6))
Mean_value_of_the_matrix=np.mean(arr)
print("mean:",Mean_value_of_the_matrix)

mean: 0.571315025978174
